jikkou.provider.kafka.config.client {
  bootstrap.servers = ${KAFKA_BOOTSTRAP_SERVERS}
  security.protocol = "SASL_PLAINTEXT"
  sasl.mechanism = "PLAIN"
  sasl.jaas.config = ${JIKKOU_KAFKA_SASL_JAAS_CONFIG}
}
